server {
    listen 8080;
    host 127.0.0.1;
    server_name alpha.local;
    root www/alpha/;
    index index.html;
}

server {
    listen 8080;
    host 127.0.0.1;
    server_name beta.local;
    root www/beta/;
    index index.html;
}